name: L1 Prediksi-Kan Automated Cron

on:
  schedule:
    # Mengeksekusi data Tengah Pekan (Setiap Selasa pukul 14:00 UTC / 22:00 WITA)
    - cron: '0 14 * * 2'
    
    # Mengeksekusi data Akhir Pekan (Setiap Jumat pukul 18:00 UTC / Sabtu 02:00 WITA)
    - cron: '0 18 * * 5'
    
  # Memungkinkan Anda menekan tombol "Run workflow" secara manual di menu GitHub Actions
  workflow_dispatch: 

jobs:
  trigger-fetch-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Django API Cron Endpoint
        run: |
          curl -X GET "https://l1prediksi-api.onrender.com/api/cron-trigger/" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET_KEY }}"